name: Delete test environment
on: 
  delete: {}
  deployment: {}
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Compute deployment name domain
        run: |
            echo "REFFF ${GITHUB_REF}"
            echo "${{ toJson(github) }}"
