name: Delete test environment
on: 
  delete: {}
  pull_request:
  types:
    - opened
    - reopened
    - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Compute deployment name domain
        run: |
            echo "${{ toJson(github) }}"
